### PR TITLE
Use nightly rustfmt to control comment wrapping and import formatting

### PR DESCRIPTION
**Pull request by svix-jplatte**
## Motivation

This makes some things more uniform (e.g. comment width, import grouping).

## Solution

Use some nightly-only rustfmt configuration options.

This change will result in occasional extra CI complaints, but you can

<details><summary>set up your local development environment to use nightly rustfmt</summary>

### For VSCode

To set up auto-format with nightly rustfmt:

```json
"rust-analyzer.rustfmt.extraArgs": [
    "+nightly"
],
```

To set up formatting on save:

```json
"editor.formatOnSave": true,
```

or just for Rust:

```json
"[rust]": {
    "editor.formatOnSave": true
},
```

### For Sublime Text

See [Owen's comment below](https://github.com/svix/omniqueue-rs/pull/54#issuecomment-1973966099).

</details>

<details><summary>... or fix those CI complaints whenever the come up</summary>

by executing

```sh
cargo +nightly fmt
```

</details>

## Further notes

`wrap_comments` sometimes leaves over-long comment lines even though they can easily be re-wrapped so I fixed up those instances by hand.

Would also be possible to set a wider line length for comments if you prefer.

### CODE REVIEW

**Comment by svix-james** [comment]
Why do we want to use nightly for formatting?

**Comment by svix-jplatte** [comment]
Because the configuration options I added to `.rustfmt.toml`, which make some things more uniform (e.g. comment width, import grouping) are only available on nightly rustfmt. (note that stable rustfmt won't undo any of the changes nightly rustfmt made here)

**Review by svix-onelson — COMMENTED** [review]
I don't suppose there's a way to set "use +nightly for rustfmt" in a toolchain file or something? I am going to forget and CI is going to bark at me.

I suppose a `justfile` could help make it so I don't have to think about it.

**Comment by svix-jplatte** [comment]
Which editor / IDE are you using? The vscode stuff above is something you can set up once, in global config and it shouldn't cause any issues for repos where there is no `.rustfmt.toml` (nightly rustfmt behaves exactly the same as stable rustfmt then, except for rare bugs).

**Comment by svix-onelson** [comment]
> Which editor / IDE are you using? The vscode stuff above is something you can set up once, in global config and it shouldn't cause any issues for repos where there is no `.rustfmt.toml` (nightly rustfmt behaves exactly the same as stable rustfmt then, except for rare bugs).

I'm _currently_ using sublime text, so the LSP config has proximity to what you shared for vscode. I've just had plenty of cases where the on-save formatting doesn't apply and I end up using the CLI to catch up.

It's fine, I can live with it 🤣

**Comment by svix-onelson** [comment]
> But I have an intrinsic fear of nightly and am worried it may cause local dev issues, or occasional build weirdness, to have it in CI.

I share this a little bit, but I think in practice it's less of a worry when we're just talking about rustfmt versus using nightly for the builds.

**Review by svix-onelson — APPROVED** [review]

**Comment by svix-jplatte** [comment]
I think one "defer to other ppl" and one "I can live with it" makes it a bit questionable whether we should actually do this. I can certainly also live with not doing this :sweat_smile:

@svix-aaron1011 @svix-lucho what's your take on this?

**Comment by svix-lucho** [comment]
> I think one "defer to other ppl" and one "I can live with it" makes it a bit questionable whether we should actually do this. I can certainly also live with not doing this 😅
> 
> @svix-aaron1011 @svix-lucho what's your take on this? Issue description is updated with some details now.

I'm ok 

> I think one "defer to other ppl" and one "I can live with it" makes it a bit questionable whether we should actually do this. I can certainly also live with not doing this 😅
> 
> @svix-aaron1011 @svix-lucho what's your take on this? Issue description is updated with some details now.

considering we can do `cargo +nightly fmt`, I'm ok with this (no strong preference though). I like the better import grouping :)

**Pull request merged**
