### PR TITLE
Allow retrying Delivery::{ack, nack}

### PR DESCRIPTION
**Pull request by svix-jplatte**
… by returning `self` on failure.

Also improve docs a little bit.

### CODE REVIEW

**Review by svix-gabriel — DISMISSED** [review]
I understand the motivation, but conceptually I actually like that `ack`/`nack` consumes the delivery, since a delivery shouldn't be modified after it's been successfully `ack`/`nack`ed.

I think a better approach would be to embed `Self` in one of the return values in the Error condition. That way, you could only retry acks/nacks if those operations failed.

That might be a more complicated change though, so I'm fine approving as is.

**Comment by svix-jplatte** [comment]
It's not much more complicated. And the server code has to change in [weird ways](https://github.com/svix/svix-webhooks/pull/1188#discussion_r1479573181) in either case, FWIW.

**Comment by svix-gabriel** [comment]
Lets try that then. If it ends up being too complicated, I can just merge this as is.

**Review by svix-gabriel — APPROVED** [review]
LGTM (if you update the PR title and message I can merge)

**Comment by svix-jplatte** [comment]
Right, missed that. Done.

**Pull request merged**
